### ISSUE TITLE
[FEAT] 회사 서비스 개발

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-backend#1]
## 📝 Description
회사 테이블 CRUD 로직 구성

## 📍 Todo
- [x] 회사 엔티티 개발
- [x] 회사 리포지토리 개발
- [x] 회사 요청/응답 DTO 개발
- [x] 회사 서비스 개발
- [x] 회사 컨트롤러 개발
- [x] 회사 서비스 테스트 코드 작성
