### ISSUE TITLE
[FEAT] 커스터머 출고 정보 제공 로직 개발

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-backend#115]
## 📝 Description
커스터머 메인 뷰에서 사용하는 출고 관련 로직 및 API 개발

## 📍 Todo
- [ ] 일일 출고 내역 요약 조회
- [ ] 최근 출고 거래 내역 조회
- [ ] 최다 매출 회사 조회 기능 구현
