### ISSUE TITLE
[FEAT] 커스터머 팔로우 기능 구현

### ISSUE THREAD

**Issue by jang643** [8-palbochae/seahere-backend#136]
## 📝 Description
설명을 작성하세요.

## 📍 Todo
- [x] 커스터머 팔로우/언팔로우 구현
- [x] 팔로우 회사 목록 조회
- [x] 출고 요청 및 회사 조회 시 팔로우 여부 표시
- [x] 주거래업체 선정
