### ISSUE TITLE
[FEAT] 이메일로 커스터머 회원 가입 구현

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-backend#15]
## 📝 Description
회원/직원 구분을 Role 로 함에 따라서 직원/회원 테이블 통합
이메일로 가입 시 커스터머 회원 가입 기능 구현

## 📍 Todo
- [x] 회원/직원 테이블 반정규화로 인한 엔티티 수정
- [x] 회원가입 요청 DTO 수정
- [x] 회원가입 요청 서비스 수정
- [x] 회원 가입 컨트롤러 구현
- [x] 테스트 코드 작성
