### ISSUE TITLE
[FEAT] CEO 직원 브로커 팀 추가 로직 구현

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-backend#67]
## 📝 Description
CEO가 허가되지 않은 직원 이메일로 직원 팀에 등록하는 로직 구현

## 📍 Todo
- [ ] CEO 직원 브로커 허가 서비스 구현
- [ ] CEO 직원 브로커 허가 컨트롤러 구현
- [ ] 테스트 코드 작성
