### ISSUE TITLE
[Feat] 거래내역 보내주는 백엔드 기능

### ISSUE THREAD

**Issue by wjdrltjr5** [8-palbochae/seahere-backend#75]
## 📝 Description
거래내역 보내주는 백엔드 기능

## 📍 Todo
- [ ] 각각의 일자별 카운팅 합치기
- [ ] 각 날짜별 데이터 보내주기
- [ ] 무한 스크롤 적용해보기
