### ISSUE TITLE
[FEAT] 회사 검색 페이징 기능 구현

### ISSUE THREAD

**Issue by kimdodo97** [8-palbochae/seahere-backend#76]
## 📝 Description
회사 정보를 조회하는 기능 구현
페이징 및 검색어 추가 기능

## 📍 Todo
- [x] 회사 페이징 Query DSL 리포지토리 구현
- [x] 페이징 조회 서비스 구현
- [x] 페이징 조회 컨트롤러 구현
